### ISSUE TITLE
Markov Chain bot

### ISSUE THREAD

**Issue by ainurnish** [goelp14/RockPaperScissors#1] opened 2019-04-17 02:56 UTC
Firstly, thank you for sharing your code because I'm working on RPS as well for a project.
I tried understanding the Markov chain bot you used in the game but I encountered a problem when testing it. I'm not sure if it is supposed to work that way so yea.

1. Transition matrix elements all equal to zero when game is exited
2. When the I input Rock as the selection, the result is always tied no matter ; either inputted simultaneously or not. 
![1](https://user-images.githubusercontent.com/49703420/56257609-5f1a5900-60ff-11e9-9a1b-48699c93c6ae.PNG)

**Comment by goelp14** [comment] 2019-04-17 05:15
Hi @klutzj! Thank you for taking a look at my code! I took another look and tested it as it is. I have not encountered any of the problems as you described above (the transition matrix prints out values other than 0 and if you keep playing rock you start losing every time). I tested both the clean version and the final project. As such, I am not able to determine the issue so if you can document or point it out more clearly that would be helpful. 

A few possibilities:
1) You are not playing in expert mode (where the Markov Chain program is)
    a) the win percentage shouldn't be so high when played normally
2)  You are printing the transition matrices in relation to something else.

Also, what do you mean by inputting simultaneously?

**Comment by goelp14** [comment] 2019-07-16 00:18
I cannot reproduce this problem so I am closing this issue.

**Closed as completed by goelp14** 2019-07-16 00:18 UTC
